-- 02_junctions_create.sql

REM ************************************************************
REM este creat tabelul SPONSORIZARI pentru a retine informatii *
REM despre contractele dintre ECHIPE si SPONSORI in detaliu    *
REM ************************************************************
PROMPT ****** creating SPONSORIZARI table...

CREATE TABLE sponsorizari (
    id_sponsorizare NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 20000 CACHE 20 NOORDER),
    id_echipa     NUMBER NOT NULL,
    id_sponsor    NUMBER NOT NULL,
    data_inceput  DATE NOT NULL,
    data_sfarsit  DATE,
    suma_contract NUMBER,

    CONSTRAINT pk_sponsorizare PRIMARY KEY (id_sponsorizare),
    CONSTRAINT fk_echipa_sponsorizata FOREIGN KEY (id_echipa)
        REFERENCES echipe(id_echipa) ON DELETE CASCADE,
    CONSTRAINT fk_sponsor FOREIGN KEY (id_sponsor)
        REFERENCES sponsori(id_sponsor) ON DELETE CASCADE,
    CONSTRAINT chk_perioada_valida_sponsorizare CHECK (data_sfarsit >= data_inceput)
);


REM ******************************************************************
REM este creat tabelul ISTORIC_CONTRACTE pentru a retine informatii  *
REM cu privire la relatiile dintre MEMBRI si ECHIPE la care au jucat *
REM ******************************************************************
PROMPT ****** creating ISTORIC_CONTRACTE table...

CREATE TABLE istoric_contracte (
    id_contract NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 200000 CACHE 20 NOORDER),
    id_membru     NUMBER NOT NULL,
    id_echipa     NUMBER NOT NULL,
    data_inceput  DATE NOT NULL,
    data_sfarsit  DATE,
    salariu_lunar NUMBER,

    CONSTRAINT pk_contract PRIMARY KEY (id_contract),
    CONSTRAINT fk_membru FOREIGN KEY (id_membru)
        REFERENCES membri(id_membru) ON DELETE CASCADE,
    CONSTRAINT fk_echipa_contract FOREIGN KEY (id_echipa)
        REFERENCES echipe(id_echipa) ON DELETE CASCADE,
    CONSTRAINT chk_perioada_valida_contract CHECK (data_sfarsit >= data_inceput)
);


REM *****************************************************************************
REM este creat tabelul STATISTICI_INDIVIDUALE pentru a retine informatii despre *
REM performanta individuala pentru JUCATORI participanti din cadrul unor RUNDE  *
REM *****************************************************************************
PROMPT ****** creating STATISTICI_INDIVIDUALE table...

CREATE TABLE statistici_individuale (
    id_runda      NUMBER NOT NULL,
    id_jucator    NUMBER NOT NULL,
    kills         INTEGER DEFAULT 0 NOT NULL,
    assists       INTEGER DEFAULT 0 NOT NULL,
    damage        INTEGER DEFAULT 0 NOT NULL,
    headshots     INTEGER DEFAULT 0 NOT NULL,
    flash_assists INTEGER DEFAULT 0 NOT NULL,
    died          INTEGER DEFAULT 0 NOT NULL,
    id_jucator_ucigas NUMBER,
    time_of_death VARCHAR2(8),

    CONSTRAINT pk_statistica PRIMARY KEY (id_runda, id_jucator),
    CONSTRAINT fk_runda FOREIGN KEY (id_runda)
        REFERENCES runde(id_runda) ON DELETE CASCADE,
    CONSTRAINT fk_jucator FOREIGN KEY (id_jucator)
        REFERENCES jucatori(id_jucator) ON DELETE CASCADE,
    CONSTRAINT fk_jucator_ucigas FOREIGN KEY (id_jucator_ucigas)
        REFERENCES jucatori(id_jucator) ON DELETE SET NULL,
    CONSTRAINT chk_kls CHECK (kills BETWEEN 0 AND 5),
    CONSTRAINT chk_ast CHECK (assists BETWEEN 0 AND 5),
    CONSTRAINT chk_dmg CHECK (damage BETWEEN 0 AND 500),
    CONSTRAINT chk_hss CHECK (headshots BETWEEN 0 AND 5),
    CONSTRAINT chk_fla CHECK (flash_assists BETWEEN 0 AND 5),
    CONSTRAINT chk_ded CHECK (died IN (0, 1))
);


REM *****************************************************************
REM este creat tabelul USER_MEMBRI_FAV pentru a retine informatii   *
REM despre preferintele utilizatorilor in cadrul unui membru        *
REM *****************************************************************
PROMPT ****** creating USER_MEMBRI_FAV table...

CREATE TABLE user_membri_fav (
    id_user NUMBER NOT NULL,
    id_membru NUMBER NOT NULL,

    CONSTRAINT pk_user_membru PRIMARY KEY (id_user, id_membru),
    CONSTRAINT fk_fav_user FOREIGN KEY (id_user) REFERENCES utilizatori(id_user) ON DELETE CASCADE,
    CONSTRAINT fk_fav_membru FOREIGN KEY (id_membru) REFERENCES membri(id_membru) ON DELETE CASCADE
);


REM ***************************************************************
REM este creat tabelul USER_ECHIPE_FAV pentru a retine informatii *
REM despre preferintele utilizatorilor in cadrul unei echipe      *
REM ***************************************************************
PROMPT ****** creating USER_ECHIPE_FAV table...

CREATE TABLE user_echipe_fav (
    id_user NUMBER NOT NULL,
    id_echipa NUMBER NOT NULL,

    CONSTRAINT pk_user_echipa PRIMARY KEY (id_user, id_echipa),
    CONSTRAINT fk_fav_user_echipa FOREIGN KEY (id_user) REFERENCES utilizatori(id_user) ON DELETE CASCADE,
    CONSTRAINT fk_fav_echipa FOREIGN KEY (id_echipa) REFERENCES echipe(id_echipa) ON DELETE CASCADE
);
