SET SERVEROUTPUT ON;

-- 1. Disable the DDL protection trigger temporarily
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER trg_protectie_schema DISABLE';
    DBMS_OUTPUT.PUT_LINE('DDL protection trigger (trg_protectie_schema) disabled.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Notice: Could not disable trg_protectie_schema (might not exist or insufficient privileges): ' || SQLERRM);
END;
/

-- 2. Reset identity sequences for all tables
DECLARE
    v_max NUMBER;
    v_sql VARCHAR2(1000);
BEGIN
    FOR r IN (SELECT table_name, column_name 
              FROM user_tab_identity_cols 
              WHERE table_name NOT LIKE 'BIN$%') LOOP
        v_sql := 'SELECT NVL(MAX("' || r.column_name || '"), 0) FROM "' || r.table_name || '"';
        BEGIN
            EXECUTE IMMEDIATE v_sql INTO v_max;
            IF v_max > 0 THEN
                v_sql := 'ALTER TABLE "' || r.table_name || '" MODIFY ("' || r.column_name || '" GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))';
                EXECUTE IMMEDIATE v_sql;
                DBMS_OUTPUT.PUT_LINE('Successfully reset ' || r.table_name || '.' || r.column_name || ' (max: ' || v_max || ')');
            ELSE
                DBMS_OUTPUT.PUT_LINE('Table ' || r.table_name || ' is empty, sequence unchanged.');
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Error resetting ' || r.table_name || '.' || r.column_name || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

-- 3. Re-enable the DDL protection trigger
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER trg_protectie_schema ENABLE';
    DBMS_OUTPUT.PUT_LINE('DDL protection trigger (trg_protectie_schema) re-enabled.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: Could not re-enable trg_protectie_schema: ' || SQLERRM);
END;
/
EXIT;
